const tripDays=[
{date:'2026-08-28',day:'D1 · 금',place:'삿포로',lat:43.0618,lon:141.3545},
{date:'2026-08-29',day:'D2 · 토',place:'비에이',lat:43.5883,lon:142.4669},
{date:'2026-08-30',day:'D3 · 일',place:'샤코탄',lat:43.3000,lon:140.6000},
{date:'2026-08-31',day:'D4 · 월',place:'도야호',lat:42.6036,lon:140.8650},
{date:'2026-09-01',day:'D5 · 화',place:'노보리베츠',lat:42.4923,lon:141.1445}
];
const schedule=[
{key:'d1-flight',date:'2026-08-28',time:'11:10',title:'✈️ WE531 · 신치토세로 출발',desc:'PARATA AIR · ICN 11:10 → CTS 13:45',nav:false},
{key:'d1-arrive',date:'2026-08-28',time:'13:45',title:'🛬 신치토세공항 도착',desc:'입국·수하물 후 렌터카 셔틀',dest:'New Chitose Airport, Hokkaido, Japan',lat:42.7752,lon:141.6923,nav:false},
{key:'d1-rental',date:'2026-08-28',time:'15:00',title:'🚙 렌터카 수령 · 삿포로 출발',desc:'ETC·NOC 확인 후 출발',dest:'Sapporo, Hokkaido, Japan',lat:43.0618,lon:141.3545,nav:true},
{key:'d1-hotel',date:'2026-08-28',time:'16:30',title:'🏨 삿포로 숙소 체크인',desc:'차를 두고 중심가로 이동',dest:'Chateau Hiragishi Sapporo',lat:43.0324,lon:141.3740,nav:true},
{key:'d1-bic',date:'2026-08-28',time:'17:30',title:' 비ック카메라 삿포로 Apple Shop',desc:'현재 영업 중인 Apple Shop · 5층',dest:'Bic Camera Sapporo Apple Shop, Hokkaido',lat:43.0680,lon:141.3510,nav:true},
{key:'d1-oldapple',date:'2026-08-28',time:'18:10',title:' 구 Apple Store Sapporo 자리',desc:'2006–2016 직영점이 있던 자리',dest:'3-8-20 Minami 1 Jonishi, Chuo Ward, Sapporo, Hokkaido',lat:43.0589,lon:141.3519,nav:true,optional:true},
{key:'d1-city',date:'2026-08-28',time:'18:30',title:'🍜 오도리 · 다누키코지 · 스스키노',desc:'첫날 저녁과 야간 산책',dest:'Susukino, Sapporo, Hokkaido',lat:43.0554,lon:141.3534,nav:true},
{key:'d1-moiwa',date:'2026-08-28',time:'21:00',title:'🌃 모이와산 야경',desc:'시야가 좋고 체력이 남으면 선택',dest:'Mt. Moiwa Ropeway, Sapporo, Hokkaido',lat:43.0246,lon:141.3227,nav:true,optional:true},
{key:'d2-depart',date:'2026-08-29',time:'06:30',title:'🌅 삿포로 출발',desc:'후라노·비에이로 이동',dest:'Farm Tomita, Hokkaido',lat:43.4173,lon:142.4253,nav:true},
{key:'d2-tomita',date:'2026-08-29',time:'09:00',title:'🌼 Farm Tomita',desc:'계절 꽃과 후라노 풍경',dest:'Farm Tomita, Hokkaido',lat:43.4173,lon:142.4253,nav:true},
{key:'d2-shikisai',date:'2026-08-29',time:'10:30',title:'🌈 Shikisai-no-Oka',desc:'8월 말 꽃밭 핵심 포인트',dest:'Shikisai-no-Oka, Biei, Hokkaido',lat:43.5290,lon:142.4650,nav:true},
{key:'d2-lunch',date:'2026-08-29',time:'12:00',title:'🍛 비에이 점심',desc:'점심 후 구릉 드라이브',dest:'Biei, Hokkaido',lat:43.5883,lon:142.4669,nav:true},
{key:'d2-patchwork',date:'2026-08-29',time:'13:00',title:'🌾 패치워크 로드',desc:'목적지보다 길 자체를 즐기기',dest:'Patchwork Road Biei, Hokkaido',lat:43.6044,lon:142.4446,nav:true},
{key:'d2-bluepond',date:'2026-08-29',time:'15:00',title:'💎 청의 호수',desc:'빛에 따라 달라지는 물빛',dest:'Shirogane Blue Pond, Biei, Hokkaido',lat:43.4935,lon:142.6140,nav:true},
{key:'d2-falls',date:'2026-08-29',time:'15:45',title:'💦 시라히게 폭포',desc:'청의 호수와 함께 묶기',dest:'Shirahige Falls, Biei, Hokkaido',lat:43.4743,lon:142.6391,nav:true},
{key:'d2-checkin',date:'2026-08-29',time:'17:30',title:'🏨 후라노 숙소 체크인',desc:'잠깐 쉬고 저녁 산책 준비',dest:'Furano, Hokkaido',lat:43.3420,lon:142.3830,nav:true},
{key:'d2-ningle',date:'2026-08-29',time:'18:30',title:'🌲 Ningle Terrace',desc:'불 켜진 숲속 오두막 산책',dest:'Ningle Terrace, Furano, Hokkaido',lat:43.3235,lon:142.3573,nav:true},
{key:'d3-depart',date:'2026-08-30',time:'06:30',title:'☕ 후라노 출발',desc:'샤코탄으로 장거리 이동',dest:'Cape Kamui, Hokkaido',lat:43.3340,lon:140.3470,nav:true},
{key:'d3-kamui',date:'2026-08-30',time:'11:00',title:'🌊 신카무이곶',desc:'강풍 통제 여부 먼저 확인',dest:'Cape Kamui, Shakotan, Hokkaido',lat:43.3340,lon:140.3470,nav:true},
{key:'d3-uni',date:'2026-08-30',time:'12:45',title:'🟠 샤코탄 생우니 점심',desc:'성게 시즌 막바지',dest:'Shakotan Uni Don, Hokkaido',lat:43.2985,lon:140.5988,nav:true},
{key:'d3-shimamui',date:'2026-08-30',time:'14:15',title:'🪨 시마무이 해안',desc:'전망대 중심으로 짧게',dest:'Shimamui Coast, Shakotan, Hokkaido',lat:43.2760,lon:140.4640,nav:true},
{key:'d3-sakaimachi',date:'2026-08-30',time:'16:10',title:'🛍️ 오타루 사카이마치',desc:'상점 닫기 전 먼저 둘러보기',dest:'Sakaimachi Street, Otaru, Hokkaido',lat:43.1906,lon:141.0075,nav:true},
{key:'d3-canal',date:'2026-08-30',time:'17:20',title:'🌆 오타루 운하',desc:'해질 무렵부터 야경까지',dest:'Otaru Canal, Hokkaido',lat:43.1987,lon:140.9947,nav:true},
{key:'d3-dinner',date:'2026-08-30',time:'18:30',title:'🍣 오타루 스시 · 숙박',desc:'저녁 후 운하 도보권에서 숙박',dest:'Sushi Otaru Hokkaido',lat:43.1907,lon:140.9947,nav:true},
{key:'d4-depart',date:'2026-08-31',time:'08:30',title:'🚙 오타루 출발',desc:'국도 393호 → 요테이산',dest:'Fukidashi Park, Hokkaido',lat:42.8582,lon:140.8707,nav:true},
{key:'d4-fukidashi',date:'2026-08-31',time:'10:15',title:'🏔️ 후키다시 공원',desc:'요테이산 자락에서 휴식',dest:'Fukidashi Park, Kyogoku, Hokkaido',lat:42.8582,lon:140.8707,nav:true},
{key:'d4-niseko',date:'2026-08-31',time:'11:30',title:'🥪 니세코 · 요테이산 드라이브',desc:'전망 좋은 길과 점심',dest:'Niseko, Hokkaido',lat:42.8048,lon:140.6874,nav:true},
{key:'d4-toya',date:'2026-08-31',time:'13:30',title:'💙 도야호',desc:'호숫가와 전망 포인트',dest:'Lake Toya, Hokkaido',lat:42.6036,lon:140.8650,nav:true},
{key:'d4-jigoku',date:'2026-08-31',time:'16:30',title:'🌋 노보리베츠 지옥계곡',desc:'체크인 전 가볍게 산책',dest:'Noboribetsu Jigokudani, Hokkaido',lat:42.4970,lon:141.1435,nav:true},
{key:'d4-ryokan',date:'2026-08-31',time:'17:30',title:'♨️ 노보리베츠 료칸',desc:'가이세키 + 노천탕으로 마무리',dest:'Noboribetsu Onsen, Hokkaido',lat:42.4923,lon:141.1445,nav:true},
{key:'d5-breakfast',date:'2026-09-01',time:'07:30',title:'🍚 조식 · 마지막 온천',desc:'체크아웃 준비',nav:false},
{key:'d5-morning',date:'2026-09-01',time:'08:30',title:'🌋 지옥계곡 · 오유누마',desc:'전날 못 봤다면 짧게',dest:'Oyunuma Pond, Noboribetsu, Hokkaido',lat:42.5017,lon:141.1550,nav:true,optional:true},
{key:'d5-depart',date:'2026-09-01',time:'09:45',title:'🚙 노보리베츠 출발',desc:'주유와 반납시간 확보',dest:'New Chitose Airport, Hokkaido',lat:42.7752,lon:141.6923,nav:true},
{key:'d5-returncar',date:'2026-09-01',time:'10:50',title:'⛽ 주유 · 렌터카 반납',desc:'영수증 보관 후 셔틀 이동',dest:'New Chitose Airport Rental Car, Hokkaido',lat:42.7752,lon:141.6923,nav:true},
{key:'d5-airport',date:'2026-09-01',time:'11:20',title:'🧳 신치토세공항 · 체크인',desc:'점심·쇼핑 후 탑승',dest:'New Chitose Airport, Hokkaido',lat:42.7752,lon:141.6923,nav:true},
{key:'d5-flight',date:'2026-09-01',time:'14:10',title:'✈️ WE532 · 인천으로 출발',desc:'CTS 14:10 → ICN 17:10',nav:false},
{key:'d5-arrive',date:'2026-09-01',time:'17:10',title:'🇰🇷 인천 도착',desc:'4박 5일 홋카이도 로드트립 종료',nav:false}
];
const bookingNights=[
{dayId:'day1',label:'삿포로',place:'Sapporo, Hokkaido, Japan',checkin:'2026-08-28',checkout:'2026-08-29'},
{dayId:'day2',label:'후라노',place:'Furano, Hokkaido, Japan',checkin:'2026-08-29',checkout:'2026-08-30'},
{dayId:'day3',label:'오타루',place:'Otaru, Hokkaido, Japan',checkin:'2026-08-30',checkout:'2026-08-31'},
{dayId:'day4',label:'노보리베츠',place:'Noboribetsu Onsen, Hokkaido, Japan',checkin:'2026-08-31',checkout:'2026-09-01'}
];
const routePoints=[
['신치토세공항',42.7752,141.6923],['삿포로',43.0618,141.3545],['BIC Apple Shop',43.0680,141.3510],['Farm Tomita',43.4173,142.4253],['Shikisai-no-Oka',43.5290,142.4650],['청의 호수',43.4935,142.6140],['Ningle Terrace',43.3235,142.3573],['신카무이곶',43.3340,140.3470],['시마무이 해안',43.2760,140.4640],['오타루',43.1987,140.9947],['후키다시 공원',42.8582,140.8707],['니세코',42.8048,140.6874],['도야호',42.6036,140.8650],['노보리베츠',42.4923,141.1445],['신치토세공항',42.7752,141.6923]
];
let map=null,myMarker=null,wakeLock=null,deferredPrompt=null,currentStop=null,toastTimer=null;
const $=id=>document.getElementById(id);
const todayISO=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const japanClock=()=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Tokyo',month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
const dt=s=>new Date(`${s.date}T${s.time}:00+09:00`);
const isDone=s=>localStorage.getItem('hk-'+s.key)==='1';
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function wx(c){if(c===0)return['☀️','맑음'];if([1,2].includes(c))return['🌤️','대체로 맑음'];if(c===3)return['☁️','흐림'];if([45,48].includes(c))return['🌫️','안개'];if([51,53,55,56,57].includes(c))return['🌦️','이슬비'];if([61,63,65,66,67,80,81,82].includes(c))return['🌧️','비'];if([71,73,75,77,85,86].includes(c))return['🌨️','눈'];if([95,96,99].includes(c))return['⛈️','뇌우'];return['🌥️','변동']}
function renderWeatherLoading(){const now=todayISO();$('weatherGrid').innerHTML=tripDays.map((d,i)=>`<div class="weather ${d.date===now?'today':''}"><div class="day">${d.day}</div><div class="place">${d.place}</div><div class="loading" id="w${i}">불러오는 중…</div></div>`).join('')}
async function loadOneWeather(d,i){const url=`https://api.open-meteo.com/v1/forecast?latitude=${d.lat}&longitude=${d.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max,sunrise,sunset&timezone=Asia%2FTokyo&forecast_days=16`;try{const r=await fetch(url);if(!r.ok)throw new Error();const j=await r.json();const x=j.daily.time.indexOf(d.date);if(x<0)throw new Error();const [icon,label]=wx(j.daily.weather_code[x]),wind=Math.round(j.daily.wind_speed_10m_max[x]),rain=j.daily.precipitation_probability_max[x],sun=(j.daily.sunset[x]||'').slice(11,16);let risk='';if(d.place==='샤코탄'&&wind>=25)risk='<div class="risk">💨 바람 강한 예보 · 곶 개방 별도 확인</div>';else if(rain>=60)risk='<div class="risk">☔ 우천 대비</div>';$('w'+i).outerHTML=`<div id="w${i}"><div class="wx" title="${label}">${icon}</div><div class="temp">${Math.round(j.daily.temperature_2m_max[x])}° / ${Math.round(j.daily.temperature_2m_min[x])}°</div><div class="rain">☔ ${rain}% · ${label}</div><div class="wind">💨 최대 ${wind} km/h</div><div class="sun">🌇 일몰 ${sun}</div>${risk}</div>`}catch(e){$('w'+i).innerHTML='날씨 조회 실패<br><small>다시 갱신해보세요</small>'}}
function refreshWeather(){renderWeatherLoading();tripDays.forEach(loadOneWeather);toast('여행지 날씨를 갱신합니다')}
function restoreDone(){document.querySelectorAll('.stop[data-key]').forEach(el=>{if(localStorage.getItem('hk-'+el.dataset.key)==='1')el.classList.add('done')})}
function toggleDone(btn){const el=btn.closest('.stop');el.classList.toggle('done');localStorage.setItem('hk-'+el.dataset.key,el.classList.contains('done')?'1':'0');updateNowCard();updateProgress()}
function markToday(){const now=todayISO();document.querySelectorAll('.day-card').forEach(c=>{if(c.dataset.date===now)c.classList.add('current')})}
function getCurrentStop(){const now=new Date(),today=todayISO();if(today<'2026-08-28')return schedule[0];if(today>'2026-09-01')return null;const list=schedule.filter(s=>s.date===today&&!isDone(s));if(!list.length)return null;return list.find(s=>dt(s)>=new Date(now.getTime()-45*60000))||list[list.length-1]}
function countdownTo(date){let ms=date-new Date();if(ms<=0)return '시간 도달';const min=Math.floor(ms/60000),d=Math.floor(min/1440),h=Math.floor((min%1440)/60),m=min%60;if(d)return `${d}일 ${h}시간`;if(h)return `${h}시간 ${m}분`;return `${m}분`}
function updateNowCard(){currentStop=getCurrentStop();$('nowClock').textContent=japanClock();if(!currentStop){$('nowTitle').textContent=todayISO()>'2026-09-01'?'🏁 여행 완료':'✅ 오늘 일정 완료';$('nowDesc').textContent=todayISO()>'2026-09-01'?'홋카이도 로드트립 종료.':'오늘 일정은 모두 체크했습니다. 여유롭게 즐기세요.';$('nowNavBtn').style.display='none';$('nowJumpBtn').style.display='none'}else{$('nowTitle').textContent=currentStop.title;$('nowDesc').textContent=`${currentStop.time} · ${countdownTo(dt(currentStop))} · ${currentStop.desc}`;$('nowNavBtn').style.display=currentStop.nav?'inline-block':'none';$('nowJumpBtn').style.display='inline-block'}const ret=new Date('2026-09-01T14:10:00+09:00');$('returnCountdown').textContent=new Date()<ret?`귀국편까지 ${countdownTo(ret)}`:'귀국편 출발 시간 경과'}
function updateProgress(){const done=schedule.filter(isDone).length,pct=Math.round(done/schedule.length*100);$('progressFill').style.width=pct+'%';$('progressText').textContent=`전체 일정 ${done}/${schedule.length} 완료 · ${pct}%`}
function jumpToday(e){if(e)e.preventDefault();const card=[...document.querySelectorAll('.day-card')].find(c=>c.dataset.date===todayISO())||$('day1');card.scrollIntoView({behavior:'smooth',block:'start'})}
function jumpToCurrentStop(){if(!currentStop)currentStop=getCurrentStop();if(!currentStop)return;const el=$('stop-'+currentStop.key);if(el)el.scrollIntoView({behavior:'smooth',block:'center'})}
function haversine(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,p=rad(c-a),q=rad(d-b),v=Math.sin(p/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(q/2)**2;return 2*R*Math.asin(Math.sqrt(v))}
function navigateNext(){currentStop=getCurrentStop();if(!currentStop){toast('남은 일정이 없습니다');return}if(!currentStop.nav){jumpToCurrentStop();return}const fallback=()=>window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(currentStop.dest)}&travelmode=driving`,'_blank');if(!navigator.geolocation){fallback();return}$('gpsNote').textContent='현재 위치를 확인하는 중…';navigator.geolocation.getCurrentPosition(p=>{const a=p.coords.latitude,b=p.coords.longitude,km=(currentStop.lat&&currentStop.lon)?haversine(a,b,currentStop.lat,currentStop.lon):null;$('gpsNote').textContent=km?`다음 목적지까지 직선거리 약 ${km.toFixed(km<10?1:0)} km`:'현재 위치를 반영했습니다.';window.open(`https://www.google.com/maps/dir/?api=1&origin=${a},${b}&destination=${encodeURIComponent(currentStop.dest)}&travelmode=driving`,'_blank')},()=>{toast('위치 권한 없이 목적지만 엽니다');fallback()},{enableHighAccuracy:true,timeout:7000,maximumAge:60000})}
async function showMyWeather(){if(!navigator.geolocation){toast('위치 기능을 지원하지 않습니다');return}const box=$('liveWeather');box.classList.add('show');box.textContent='현재 위치와 날씨 확인 중…';navigator.geolocation.getCurrentPosition(async p=>{try{const lat=p.coords.latitude,lon=p.coords.longitude,r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,precipitation&timezone=Asia%2FTokyo`),j=await r.json(),[icon,label]=wx(j.current.weather_code);box.innerHTML=`<b>${icon} 현재 위치 날씨 · ${label}</b><br>${Math.round(j.current.temperature_2m)}°C · 체감 ${Math.round(j.current.apparent_temperature)}°C · 바람 ${Math.round(j.current.wind_speed_10m)} km/h · 강수 ${j.current.precipitation} mm`}catch(e){box.textContent='현재 날씨를 불러오지 못했습니다.'}},()=>box.textContent='위치 권한이 필요합니다.',{enableHighAccuracy:true,timeout:7000,maximumAge:60000})}
function openNearby(query){const go=(a,b)=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query+' near '+a+','+b)}`,'_blank');if(!navigator.geolocation){window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query+' near me')}`,'_blank');return}navigator.geolocation.getCurrentPosition(p=>go(p.coords.latitude,p.coords.longitude),()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query+' near me')}`,'_blank'),{timeout:5000,maximumAge:60000})}
function googleSearchUrl(query){return `https://www.google.com/search?q=${encodeURIComponent(query)}`}
function bookingSearchUrl(night){const u=new URL('https://www.booking.com/searchresults.html');u.searchParams.set('ss',night.place);u.searchParams.set('checkin',night.checkin);u.searchParams.set('checkout',night.checkout);u.searchParams.set('group_adults','2');u.searchParams.set('no_rooms','1');u.searchParams.set('group_children','0');return u.toString()}
function initSearchButtons(){const byKey=Object.fromEntries(schedule.map(s=>[s.key,s]));document.querySelectorAll('.stop[data-key]').forEach(el=>{const s=byKey[el.dataset.key];if(!s||!s.dest)return;const main=el.querySelector('.stop-main');if(!main)return;let links=main.querySelector('.map-links');if(!links){links=document.createElement('div');links.className='map-links';main.appendChild(links)}if(links.querySelector('[data-google-search]'))return;const a=document.createElement('a');a.dataset.googleSearch='1';a.target='_blank';a.rel='noopener';a.href=googleSearchUrl(s.dest);a.textContent='🔎 Google 검색';links.appendChild(a)});bookingNights.forEach(n=>{const day=$(n.dayId),actions=day&&day.querySelector('.day-actions');if(!actions||actions.querySelector('[data-booking-search]'))return;const a=document.createElement('a');a.dataset.bookingSearch='1';a.className='pill';a.target='_blank';a.rel='noopener';a.href=bookingSearchUrl(n);a.textContent=`🏨 Booking.com ${n.label} 숙소`;a.title=`${n.checkin} 체크인 · ${n.checkout} 체크아웃 · 성인 2명`;actions.appendChild(a)})}
function initMap(){map=L.map('map',{scrollWheelZoom:false}).setView([43.05,141.4],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);const ll=[];routePoints.forEach((p,i)=>{ll.push([p[1],p[2]]);const icon=L.divIcon({className:'',html:`<div class="num-marker">${i+1}</div>`,iconSize:[28,28],iconAnchor:[14,14]});L.marker([p[1],p[2]],{icon}).addTo(map).bindPopup(`<b>${p[0]}</b><br><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[0]+' Hokkaido')}">Google Maps</a><br><a target="_blank" href="${googleSearchUrl(p[0]+' Hokkaido')}">Google 검색</a>`)});L.polyline(ll,{color:'#2563eb',weight:4,opacity:.75,dashArray:'8 7'}).addTo(map);map.fitBounds(ll,{padding:[24,24]})}
function locateOnMap(){if(!navigator.geolocation){toast('위치 기능 미지원');return}navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];if(myMarker)myMarker.setLatLng(ll);else myMarker=L.circleMarker(ll,{radius:8,color:'#0284c7',fillColor:'#38bdf8',fillOpacity:.9}).addTo(map).bindPopup('현재 위치');map.setView(ll,11);myMarker.openPopup();toast('현재 위치를 지도에 표시했습니다')},()=>toast('위치 권한이 필요합니다'),{enableHighAccuracy:true,timeout:7000,maximumAge:60000})}
async function sharePlan(){const data={title:'홋카이도 4박 5일 여행 플래너',text:'홋카이도 렌터카 여행 일정',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('링크를 복사했습니다')}}catch(e){}}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('복사했습니다')}catch(e){toast('복사하지 못했습니다')}}
async function toggleWakeLock(){if(!('wakeLock' in navigator)){toast('이 브라우저는 화면 유지 기능을 지원하지 않습니다');return}try{if(wakeLock){await wakeLock.release();wakeLock=null;$('wakeBtn').innerHTML='<span>☀️</span>화면 유지'}else{wakeLock=await navigator.wakeLock.request('screen');$('wakeBtn').innerHTML='<span>🌞</span>유지 중';toast('화면을 켜둡니다')}}catch(e){toast('화면 유지 권한을 얻지 못했습니다')}}
function initNotes(){document.querySelectorAll('[data-note]').forEach(el=>{const k='hk-note-'+el.dataset.note;el.value=localStorage.getItem(k)||'';el.addEventListener('input',()=>localStorage.setItem(k,el.value))});document.querySelectorAll('[data-field]').forEach(el=>{const k='hk-field-'+el.dataset.field,existing=localStorage.getItem(k);if(existing!==null)el.value=existing;el.addEventListener('input',()=>localStorage.setItem(k,el.value))})}
function resetTrip(){if(!confirm('방문 체크와 메모를 모두 초기화할까요?'))return;Object.keys(localStorage).filter(k=>k.startsWith('hk-')).forEach(k=>localStorage.removeItem(k));location.reload()}
function onlineState(){const on=navigator.onLine;$('onlineDot').classList.toggle('off',!on);$('onlineText').textContent=on?'온라인 · 실시간 날씨 사용 가능':'오프라인 · 저장된 일정 사용 가능'}
function installApp(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.finally(()=>deferredPrompt=null)}else toast('브라우저 메뉴에서 홈 화면에 추가할 수 있습니다')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').style.display='block'});
window.addEventListener('online',onlineState);window.addEventListener('offline',onlineState);
document.addEventListener('visibilitychange',async()=>{if(wakeLock&&document.visibilityState==='visible')try{wakeLock=await navigator.wakeLock.request('screen')}catch(e){}});
document.addEventListener('DOMContentLoaded',()=>{refreshWeather();restoreDone();markToday();initSearchButtons();initMap();initNotes();updateNowCard();updateProgress();onlineState();setInterval(updateNowCard,60000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});